version: "2"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
     - mysql_data:/var/lib/mysql
    environment:
        - MYSQL_DATABASES=db
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_HOST=localhost
        - MYSQL_PORT=3306
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
    networks:
      - mysqlNet
  app:
    depends_on:
       - db
    image: golang:latest
    build: .
    volumes:
      - .:/go/src/tax
    working_dir: /go/src/tax
    ports:
      - "3000:3000"
    links:
      - db:db
    networks:
      - mysqlNet
    command: go run main/main.go
    
volumes:
 mysql_data:
    
networks:
  mysqlNet:
    driver: bridge